
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team01-f25-02
owner: ucsb-cs156-f25
repo_name: team01-f25-02
pull_requests: [{"author":{"id":"U_kgDOBdHq8Q","is_bot":false,"login":"fcataldothome","name":""},"headRefName":"pc-Items-by_id","number":50,"title":"Pc GET Id for commits","url":"https://github.com/ucsb-cs156-f25/team01-f25-02/pull/50"},{"author":{"id":"MDQ6VXNlcjcyMTY4MzQ5","is_bot":false,"login":"AgamMakkar21","name":""},"headRefName":"am-articles-get-by-id","number":49,"title":"Am articles get by","url":"https://github.com/ucsb-cs156-f25/team01-f25-02/pull/49"},{"author":{"id":"U_kgDODf0g7A","is_bot":false,"login":"m4ttblanke","name":"Matt Blanke"},"headRefName":"mb-UCSBOrganization-organization-controller","number":48,"title":"mb - create UCSB Organization controller, add GET /all and POST methods","url":"https://github.com/ucsb-cs156-f25/team01-f25-02/pull/48"},{"author":{"id":"U_kgDOBdHq8Q","is_bot":false,"login":"fcataldothome","name":""},"headRefName":"Felipe-Dinnig","number":47,"title":"Felipe dinnig - create UCSBDInningCommonsItem, add GET /all and POST methods","url":"https://github.com/ucsb-cs156-f25/team01-f25-02/pull/47"},{"author":{"id":"U_kgDOBYAf9w","is_bot":false,"login":"pewpewpew0","name":""},"headRefName":"pewpewpew0-HelpRequest-create-db","number":46,"title":"ml - create dbtable for helpRequests","url":"https://github.com/ucsb-cs156-f25/team01-f25-02/pull/46"},{"author":{"id":"MDQ6VXNlcjcyMTY4MzQ5","is_bot":false,"login":"AgamMakkar21","name":""},"headRefName":"am-articles-database","number":45,"title":"am - created Articles DB","url":"https://github.com/ucsb-cs156-f25/team01-f25-02/pull/45"},{"author":{"id":"MDQ6VXNlcjYxODkyNjc3","is_bot":false,"login":"Jeff496","name":"Jeffrey Keem"},"headRefName":"jeff496-RecommendationRequest-create-db","number":44,"title":"jeff496 - create database table for recommendation requests","url":"https://github.com/ucsb-cs156-f25/team01-f25-02/pull/44"},{"author":{"id":"U_kgDODf0g7A","is_bot":false,"login":"m4ttblanke","name":"Matt Blanke"},"headRefName":"mb-UCSBOrganization-create-db","number":43,"title":"mb - create database table for UCSBOrganization","url":"https://github.com/ucsb-cs156-f25/team01-f25-02/pull/43"}]
