
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team01-f25-02
owner: ucsb-cs156-f25
repo_name: team01-f25-02
pull_requests: [{"author":{"id":"U_kgDODf0g7A","is_bot":false,"login":"m4ttblanke","name":"Matt Blanke"},"headRefName":"mb-UCSBOrganization-create-db","number":43,"title":"mb - create database table for UCSBOrganization","url":"https://github.com/ucsb-cs156-f25/team01-f25-02/pull/43"}]
