
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team01-f25-02
owner: ucsb-cs156-f25
repo_name: team01-f25-02
pull_requests: [{"author":{"id":"MDQ6VXNlcjYxODkyNjc3","is_bot":false,"login":"Jeff496","name":"Jeffrey Keem"},"headRefName":"jeff496-delete-for-RecommendationRequest","number":67,"title":"Jeff496 - delete for recommendation request","url":"https://github.com/ucsb-cs156-f25/team01-f25-02/pull/67"},{"author":{"id":"U_kgDOBnWR7A","is_bot":false,"login":"gavincao2023","name":"Gavin Cao"},"headRefName":"gavin-MenuItemReview-delete","number":66,"title":"Gavin menu item review delete","url":"https://github.com/ucsb-cs156-f25/team01-f25-02/pull/66"},{"author":{"id":"MDQ6VXNlcjYxODkyNjc3","is_bot":false,"login":"Jeff496","name":"Jeffrey Keem"},"headRefName":"jeff496-put-for-RecommendationRequest","number":65,"title":"jeff496 - PUT method for Recommendation Request table","url":"https://github.com/ucsb-cs156-f25/team01-f25-02/pull/65"},{"author":{"id":"U_kgDOBYAf9w","is_bot":false,"login":"pewpewpew0","name":""},"headRefName":"pewpewpew0-helprequest-controller","number":54,"title":"ml - create helpRequest controller, add GET (index) and POST (create) methods","url":"https://github.com/ucsb-cs156-f25/team01-f25-02/pull/54"}]
