
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team01-f25-02
owner: ucsb-cs156-f25
repo_name: team01-f25-02
pull_requests: [{"author":{"id":"U_kgDOBnWR7A","is_bot":false,"login":"gavincao2023","name":"Gavin Cao"},"headRefName":"gavin-MenuItemReview-table","number":59,"title":"Add MenuItemReview database table and migration","url":"https://github.com/ucsb-cs156-f25/team01-f25-02/pull/59"},{"author":{"id":"MDQ6VXNlcjYxODkyNjc3","is_bot":false,"login":"Jeff496","name":"Jeffrey Keem"},"headRefName":"jeff496-RecommendationRequest-get-by-id","number":58,"title":"Jeff496 - add GET by id for recommendation requests","url":"https://github.com/ucsb-cs156-f25/team01-f25-02/pull/58"},{"author":{"id":"U_kgDODf0g7A","is_bot":false,"login":"m4ttblanke","name":"Matt Blanke"},"headRefName":"mb-UCSBOrganization-delete-for-organization-table","number":57,"title":"mb - add DELETE for UCSBOrganization","url":"https://github.com/ucsb-cs156-f25/team01-f25-02/pull/57"},{"author":{"id":"U_kgDODf0g7A","is_bot":false,"login":"m4ttblanke","name":"Matt Blanke"},"headRefName":"mb-UCSBOrganization-put-for-organization-table","number":55,"title":"mb - add PUT for UCSBOrganization","url":"https://github.com/ucsb-cs156-f25/team01-f25-02/pull/55"},{"author":{"id":"U_kgDOBYAf9w","is_bot":false,"login":"pewpewpew0","name":""},"headRefName":"pewpewpew0-helprequest-controller","number":54,"title":"ml - create helpRequest controller, add GET (index) and POST (create) methods","url":"https://github.com/ucsb-cs156-f25/team01-f25-02/pull/54"}]
